prefix = "."
stop-words = "lemur-stopwords.txt"

corpus = "file.toml"
dataset = "dataset"
index = "idx"

[[analyzers]]
method = "ngram-word"
ngram = 1
    [[analyzers.filter]]
    type = "whitespace-tokenizer"

    [[analyzers.filter]]
    type = "lowercase"

    [[analyzers.filter]]
    type = "length"
    min = 2
    max = 35

[ranker]
method = "bm25"
k1 = 1.2
b = 0.75
k3 = 500
